# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

EMSingle <- function(rho, effectlen, ts, ecnum) {
    .Call(`_RNASeqEM_EMSingle`, rho, effectlen, ts, ecnum)
}

Strsplit <- function(s, delim) {
    .Call(`_RNASeqEM_Strsplit`, s, delim)
}

SplitEC <- function(ec) {
    .Call(`_RNASeqEM_SplitEC`, ec)
}

